---
- name: Auditable accounting deployment
  hosts: all
  become: true
  tasks:
    - name: Login to i3-Market Registry
      docker_login:
        registry_url: "{{REGISTRY_URL}}"
        username: "{{REGISTRY_USER}}"
        password: "{{REGISTRY_PASSWORD}}"
    
    - name: Launch Loopback instance
      docker_container:
        name: auditable-accounting        
        image: "{{REGISTRY_URL}}/auditable-accounting:latest"
        pull: yes
        env:
          ALLOWED_CORS: "{{ALLOWED_CORS}}"
          WEB3_PROVIDER_NAME: "{{WEB3_PROVIDER_NAME}}"
          WEB3_PROVIDER: "{{WEB3_PROVIDER}}"
          WEB3_SC_ADDR: "{{WEB3_SC_ADDR}}"
          WEB3_KEY: "{{WEB3_KEY}}"
          WEB3_GAS: "{{WEB3_GAS}}"
          DB_HOST: "{{DB_HOST}}"
          DB_PORT: "{{DB_PORT}}"
          DB_NAME: "{{DB_NAME}}"
          DB_USER: "{{DB_USER}}"
          DB_CA: "{{DB_CA}}"
          DB_CRT: "{{DB_CRT}}"
          DB_KEY: "{{DB_KEY}}"
        ports:
          - "{{AA_PORT}}:3000"
        state: started
      
