---
- name: Backplane deployment
  hosts: i3m-node1
  tasks:
    - name: Create backplane config files folder
      file:
        path: "backplane/certificates"
        state: directory
        mode: '0755'
        recurse: yes
        
    - name: Get config files
      get_url:
        url: "{{ item.src }}"
        dest: "backplane/{{ item.dest }}"
        url_username: "{{NEXUS_USERNAME}}"
        url_password: "{{NEXUS_PASSWORD}}"
      loop:
        - { src: "{{SECRETS_URL}}", dest: "secrets.json"}
        - { src: "{{ENV_FILE_URL}}", dest: ".env"}
        - { src: "{{CERT_FILE_URL}}", dest: "certificates/cert.crt"}
        - { src: "{{KEY_FILE_URL}}", dest: "certificates/key.key"}
        - { src: "{{CA_CERT_FILE_URL}}", dest: "certificates/ca-cert.crt"}

    - name: Login to Nexus registry
      docker_login:
        registry_url: 95.211.3.251:8123
        tls: no
        username: "{{NEXUS_USERNAME}}"
        password: "{{NEXUS_PASSWORD}}"

    - name: Run Backplane docker image
      docker_container:
        name: backplane
        image: 95.211.3.251:8123/backplane:latest
        pull: yes
        env_file: "/home/upc_victor.divi/backplane/.env"
        env:
          CERTS_PATH: /certificates
          SECRETS_PATH: /.secrets.json
        volumes:
          - "/home/upc_victor.divi/backplane/certificates:/certificates"
          - "/home/upc_victor.divi/backplane/secrets.json:/.secrets.json"
        ports:
          - 3000:3000
        state: started
    - name: Send email notification
      mail:
        host: localhost
        port: 25
        from: i3m-ansible-admin@i3-market.eu
        to: "{{item}}"
        subject: SDK-core new version available
        body: "A new version of the Backplane deployed. \nAvailable at https://95.211.3.244:3000/ ashd"
      loop: "{{RECIPIENTS}}"
      when: SEND_EMAIL
