- name: Login to Backplane registry
  hosts: i3m-node1
  community.docker.docker_login:
    registry_url: registry.gitlab.com
    username: "{{BACKPLANE_REGISTRY_USER}}"
    password: "{{BACKPLANE_REGISTRY_TOKEN}}"

- name: Pull Backplane image
  hosts: i3m-node1
  community.docker.docker_container:
    image: registry.gitlab.com/i3-market/code/wp4/backplane:latest
    pull: yes
