---
- name: Backplane deployment
  hosts: i3m-node1
  tasks:
    - name: Print pwd
      debug:
        msg:
          - "{{ lookup('env', 'PWD') }}"
          - "{{ PWD }}"
    - name: Create backplane config files folder
      file:
        path: "backplane/certificates"
        state: directory
        mode: '0755'
        recurse: yes
    - name: list dir
      shell: pwd & ls & ls "{{PWD}}"
    - name: Get config files
      get_url:
        url: "{{ item.src }}"
        dest: "backplane/{{ item.dest }}"
        headers:
          PRIVATE-TOKEN: "{{BACKPLANE_ACCESS_TOKEN}}" 
      loop:
        - { src: "{{SECRETS_URL}}", dest: "secrets.json"}
        - { src: "{{ENV_FILE_URL}}", dest: ".env"}
        - { src: "{{CERT_FILE_URL}}", dest: "certificates/cert.crt"}
        - { src: "{{KEY_FILE_URL}}", dest: "certificates/key.key"}
        - { src: "{{CA_CERT_FILE_URL}}", dest: "certificates/ca-cert.crt"}
    - name: Login to Backplane registry
      docker_login:
        registry_url: registry.gitlab.com
        username: "{{BACKPLANE_REGISTRY_USER}}"
        password: "{{BACKPLANE_REGISTRY_TOKEN}}"

    - name: Pull Backplane image
      docker_container:
        name: backplane
        image: registry.gitlab.com/i3-market/code/wp4/backplane:latest
        pull: yes
        env_file: "backplane/.env"
        volumes:
          - "{{playbook_dir}}backplane/certificates:/certificates"
          - "{{playbook_dir}}backplane/secrets.json:/.secrets.json"
        ports:
          - "3000:3000"
