---
- name: BESU nodes - folder creation
  hosts: all
  become: true
  tasks:
    - name: Creating data folder       
      file:
        path: "/var/besu"
        state: directory
        mode: '0775'    
        owner: 1000
        group: 1000
        recurse: yes

    - name: Get config files from Nexus
      get_url:
        url: "{{URL_GENESIS}}"
        dest: "/var/besu/genesis.json"
        url_username: "{{NEXUS_USER}}"
        url_password: "{{NEXUS_PASS}}"
    
    - name: Set owner for genesis.json
      file:
        path: /var/besu/genesis.json
        owner: 1000
        group: 1000

- name: BESU nodes deployment
  hosts: i3m-node1
  become: true
  tasks:
    - name: Get config files
      get_url:
        url: "{{ item.src }}"
        dest: "/var/besu/{{ item.dest }}"
        url_username: "{{NEXUS_USER}}"
        url_password: "{{NEXUS_PASS}}"
      loop:
        - { src: "{{URL_KEY1}}", dest: "key"}
        - { src: "{{URL_KEY_PUB1}}", dest: "key.pub"}
    
    - name: Set owner for key
      file:
        path: /var/besu/key
        owner: 1000
        group: 1000

    - name: Set owner for key.pub
      file:
        path: /var/besu/key.pub
        owner: 1000
        group: 1000

    - name: Run latest BESU docker image
      docker_container:
        name: besu
        image: hyperledger/besu:latest
        env:
          BESU_DATA_PATH: "/besu"
          BESU_GENESIS_FILE: "/besu/genesis.json"
          BESU_HOST_ALLOWLIST: "*"
          BESU_P2P_HOST: "0.0.0.0"
          BESU_RPC_HTTP_ENABLED: "true"
          BESU_RPC_HTTP_HOST: "0.0.0.0"
          BESU_RPC_WS_ENABLED: "true"
          BESU_RPC_WS_HOST: "0.0.0.0"
        volumes:
          - "/var/besu:/besu"
        ports:
          - 30303:30303/udp
          - 30303:30303/tcp
          - 8545:8545/tcp
          - 8546:8546/tcp
        state: started

- name: BESU nodes deployment
  hosts: i3m-node2
  become: true
  tasks:
  
    - name: Get config files
      get_url:
        url: "{{ item.src }}"
        dest: "/var/besu/{{ item.dest }}"
        url_username: "{{NEXUS_USER}}"
        url_password: "{{NEXUS_PASS}}"
      loop:
        - { src: "{{URL_KEY2}}", dest: "key"}
        - { src: "{{URL_KEY_PUB2}}", dest: "key.pub"}

    - name: Run latest BESU docker image
      docker_container:
        name: besu
        image: hyperledger/besu:latest
        env:
          BESU_DATA_PATH: "/besu"
          BESU_GENESIS_FILE: "/besu/genesis.json"
          BESU_HOST_ALLOWLIST: "*"
          BESU_P2P_HOST: "0.0.0.0"
          BESU_RPC_HTTP_ENABLED: "true"
          BESU_RPC_HTTP_HOST: "0.0.0.0"
          BESU_RPC_WS_ENABLED: "true"
          BESU_RPC_WS_HOST: "0.0.0.0"
          BESU_BOOTNODES: "{{BOOTNODE}}"
        volumes:
          - "/var/besu:/besu"
        ports:
          - 30303:30303/udp
          - 30303:30303/tcp
          - 8545:8545/tcp
          - 8546:8546/tcp
        state: started

- name: BESU nodes deployment
  hosts: i3m-node3
  become: true
  tasks:
  
    - name: Get config files
      get_url:
        url: "{{ item.src }}"
        dest: "/var/besu/{{ item.dest }}"
        url_username: "{{NEXUS_USER}}"
        url_password: "{{NEXUS_PASS}}"
      loop:
        - { src: "{{URL_KEY3}}", dest: "key"}
        - { src: "{{URL_KEY_PUB3}}", dest: "key.pub"}

    - name: Run latest BESU docker image
      docker_container:
        name: besu
        image: hyperledger/besu:latest
        env:
          BESU_DATA_PATH: "/besu"
          BESU_GENESIS_FILE: "/besu/genesis.json"
          BESU_HOST_ALLOWLIST: "*"
          BESU_P2P_HOST: "0.0.0.0"
          BESU_RPC_HTTP_ENABLED: "true"
          BESU_RPC_HTTP_HOST: "0.0.0.0"
          BESU_RPC_WS_ENABLED: "true"
          BESU_RPC_WS_HOST: "0.0.0.0"
          BESU_BOOTNODES: "{{BOOTNODE}}"
        volumes:
          - "/var/besu:/besu"
        ports:
          - 30303:30303/udp
          - 30303:30303/tcp
          - 8545:8545/tcp
          - 8546:8546/tcp
        state: started

- name: BESU nodes deployment
  hosts: i3m-node4
  become: true
  tasks:
  
    - name: Get config files
      get_url:
        url: "{{ item.src }}"
        dest: "/var/besu/{{ item.dest }}"
        url_username: "{{NEXUS_USER}}"
        url_password: "{{NEXUS_PASS}}"
      loop:
        - { src: "{{URL_KEY4}}", dest: "key"}
        - { src: "{{URL_KEY_PUB4}}", dest: "key.pub"}

    - name: Run latest BESU docker image
      docker_container:
        name: besu
        image: hyperledger/besu:latest
        env:
          BESU_DATA_PATH: "/besu"
          BESU_GENESIS_FILE: "/besu/genesis.json"
          BESU_HOST_ALLOWLIST: "*"
          BESU_P2P_HOST: "0.0.0.0"
          BESU_RPC_HTTP_ENABLED: "true"
          BESU_RPC_HTTP_HOST: "0.0.0.0"
          BESU_RPC_WS_ENABLED: "true"
          BESU_RPC_WS_HOST: "0.0.0.0"
          BESU_BOOTNODES: "{{BOOTNODE}}"
        volumes:
          - "/var/besu:/besu"
        ports:
          - 30303:30303/udp
          - 30303:30303/tcp
          - 8545:8545/tcp
          - 8546:8546/tcp
        state: started
