---
- name: BESU nodes - folder creation
  hosts: all
  become: true
  tasks:
    - name: Creating data folder       
      file:
        path: "/var/besu"
        state: directory
        mode: '0775'    
        owner: 1000
        group: 1000
        recurse: yes

    - name: Get config files from Nexus
      get_url:
        url: "{{URL_GENESIS}}"        
        url_username: "{{NEXUS_USER}}"
        url_password: "{{NEXUS_PASS}}"
        dest: "/var/besu/genesis.json"
        owner: 1000
        group: 1000        

- name: BESU deployment
  hosts: all
  become: true
  tasks:
    - name: Run docker image
      docker_container:
        name: besu
        image: hyperledger/besu:latest
        env:
          BESU_DATA_PATH: "/besu"
          BESU_GENESIS_FILE: "/besu/genesis.json"
          BESU_HOST_ALLOWLIST: "*"
          BESU_P2P_HOST: "0.0.0.0"
          BESU_RPC_HTTP_ENABLED: "true"
          BESU_RPC_HTTP_HOST: "0.0.0.0"
          BESU_RPC_WS_ENABLED: "true"
          BESU_RPC_WS_HOST: "0.0.0.0"
          BESU_BOOTNODES: "{{BOOTNODE}}"
        volumes:
          - "{{VOLUME}}:/besu"
        ports:
          - "{{PORT_P2P}}:30303/udp"
          - "{{PORT_P2P}}:30303/tcp"
          - "{{PORT_HTTP}}:8545/tcp"
          - "{{PORT_WS}}:8546/tcp"
        state: started
