---
- name: BESU preparation
  hosts: all
  become: true
  tasks:
    - name: Creating data folder       
      file:
        path: "{{VOLUME}}"
        state: directory
        mode: '0775'    
        owner: 1000
        group: 1000
        recurse: yes

    - name: Get genesis from Nexus
      get_url:
        url: "{{URL_GENESIS}}"        
        url_username: "{{NEXUS_USER}}"
        url_password: "{{NEXUS_PASS}}"
        dest: "{{VOLUME}}/genesis.json"
        owner: 1000
        group: 1000        

- name: Get keys from Nexus
  hosts: {{ item.host }}
  become: true
  tasks:
    - name: Get keys from Nexus
      get_url:
        url: "{{ item.key }}"        
        url_username: "{{NEXUS_USER}}"
        url_password: "{{NEXUS_PASS}}"
        dest: "{{VOLUME}}/key"
        owner: 1000
        group: 1000
  loop:
    - { host: 'i3m-node1', key: {{URL_KEY1}}}
    - { host: 'i3m-node2', key: {{URL_KEY2}}}
    - { host: 'i3m-node3', key: {{URL_KEY3}}}
    - { host: 'i3m-node4', key: {{URL_KEY4}}}

- name: BESU deployment
  hosts: all
  become: true
  tasks:
    - name: Run docker image
      docker_container:
        name: besu
        image: "{{IMAGE_BESU}}"
        env:
          BESU_DATA_PATH: "/besu"
          BESU_GENESIS_FILE: "/besu/genesis.json"
          BESU_HOST_ALLOWLIST: "*"
          BESU_P2P_HOST: "0.0.0.0"
          BESU_RPC_HTTP_ENABLED: "true"
          BESU_RPC_HTTP_HOST: "0.0.0.0"
          BESU_RPC_HTTP_API: "{{RPC_API_METHODS}}"
          BESU_RPC_WS_ENABLED: "true"
          BESU_RPC_WS_HOST: "0.0.0.0"
          BESU_BOOTNODES: "{{BOOTNODE}}"
        volumes:
          - "{{VOLUME}}:/besu"
        ports:
          - "{{PORT_P2P}}:30303/udp"
          - "{{PORT_P2P}}:30303/tcp"
          - "{{PORT_HTTP}}:8545/tcp"
          - "{{PORT_WS}}:8546/tcp"
        state: started
