---
- name: BESU nodes deployment
  hosts: all
  become: true
  tasks:
    - name: Create backplane config files folder
      file:
        path: "/var/backplane/certificates"
        state: directory
        mode: '0755'
        recurse: yes
        
    - name: Get config files
      get_url:
        url: "{{ item.src }}"
        dest: "/var/backplane/{{ item.dest }}"
        url_username: "{{NEXUS_USERNAME}}"
        url_password: "{{NEXUS_PASSWORD}}"
      loop:
        - { src: "{{SECRETS_URL}}", dest: "secrets.json"}
        - { src: "{{ENV_FILE_URL}}", dest: ".env"}
        - { src: "{{CERT_FILE_URL}}", dest: "certificates/cert.crt"}
        - { src: "{{KEY_FILE_URL}}", dest: "certificates/key.key"}
        - { src: "{{CA_CERT_FILE_URL}}", dest: "certificates/ca-cert.crt"}

    - name: Login to Gitlab registry
      docker_login:
        registry_url: registry.gitlab.com
        username: "{{GITLAB_REGISTRY_USER}}"
        password: "{{GITLAB_REGISTRY_TOKEN}}"

    - name: Run Backplane docker image
      docker_container:
        name: backplane
        image: registry.gitlab.com/i3-market/code/backplane/backplane-api-gateway/backplane:latest
        pull: yes
        env_file: "/var/backplane/.env"
        env:
          CERTS_PATH: /certificates
          SECRETS_PATH: /.secrets.json
          PUBLIC_URI: "http://{{ansible_default_ipv4.address}}:3000"
        volumes:
          - "/var/backplane/certificates:/certificates"
          - "/var/backplane/secrets.json:/.secrets.json"
        ports:
          - 3000:3000
        state: started

- name: Notifications    
  hosts: i3m-node2
  become: true
  tasks:
    - name: Send email notification
      mail:
        host: localhost
        port: 25
        from: admin@i3-market.eu
        to: "{{RECIPIENTS}}"
        subject: Backplane new version available
        body: "A new version of the Backplane deployed. \nAvailable at https://95.211.3.244:3000/"
      when: SEND_EMAIL
