---
- name: BESU nodes preparation
  hosts: all
  become: true
  tasks:
    - name: Create backplane config files folder       
      file:         
        path: "/var/besu/config"
        state: directory
        mode: '0755'    
        owner: root
        group: root
        recurse: yes
      file:         
        path: "/var/besu/database"
        state: directory
        mode: '0755'
        owner: root
        group: root     
        recurse: yes

    - name: Get config files
      get_url:
        url: "{{ item.src }}"
        dest: "/var/besu/config/{{ item.dest }}"
        url_username: "{{NEXUS_USER}}"
        url_password: "{{NEXUS_PASS}}"
      loop:
        - { src: "{{URL_GENESIS}}", dest: "genesis.json"}
        - { src: "{{URL_CONFIG}}", dest: "config.toml"} 

- name: BESU nodes deployment
  hosts: i3m-node1
  become: true
  tasks:
  
    - name: Get config files
      get_url:
        url: "{{ item.src }}"
        dest: "/var/besu/config/{{ item.dest }}"
        url_username: "{{NEXUS_USER}}"
        url_password: "{{NEXUS_PASS}}"
      loop:
        - { src: "{{URL_KEY1}}", dest: "key"}
        - { src: "{{URL_KEY_PUB1}}", dest: "key.pub"}

    - name: Run latest BESU docker image
      docker_container:
        name: besu
        image: hyperledger/besu:latest
        pull: yes
        env:
          BESU_CONFIG_FILE: /opt/besu/config/config.tml
        volumes:
          - "/var/besu/config:/opt/besu/config"
          - "/var/besu/database:/opt/besu/database"
        ports:
          - 30303:30303/udp
          - 30303:30303/tcp
          - 8545:8545/tcp
          - 8546:8546/tcp
        state: started

- name: BESU nodes deployment
  hosts: i3m-node2
  become: true
  tasks:
  
    - name: Get config files
      get_url:
        url: "{{ item.src }}"
        dest: "/var/besu/config/{{ item.dest }}"
        url_username: "{{NEXUS_USER}}"
        url_password: "{{NEXUS_PASS}}"
      loop:
        - { src: "{{URL_KEY2}}", dest: "key"}
        - { src: "{{URL_KEY_PUB2}}", dest: "key.pub"}

    - name: Run latest BESU docker image
      docker_container:
        name: besu
        image: hyperledger/besu:latest
        pull: yes
        env:
          BESU_CONFIG_FILE: /opt/besu/config/config.tml
          BESU_BOOTNODES: "{{BOOTNODE}}"
        volumes:
          - "/var/besu/config:/opt/besu/config"
          - "/var/besu/database:/opt/besu/database"
        ports:
          - 30303:30303/udp
          - 30303:30303/tcp
          - 8545:8545/tcp
          - 8546:8546/tcp
        state: started

- name: BESU nodes deployment
  hosts: i3m-node3
  become: true
  tasks:
  
    - name: Get config files
      get_url:
        url: "{{ item.src }}"
        dest: "/var/besu/config/{{ item.dest }}"
        url_username: "{{NEXUS_USER}}"
        url_password: "{{NEXUS_PASS}}"
      loop:
        - { src: "{{URL_KEY3}}", dest: "key"}
        - { src: "{{URL_KEY_PUB3}}", dest: "key.pub"}

    - name: Run latest BESU docker image
      docker_container:
        name: besu
        image: hyperledger/besu:latest
        pull: yes
        env:
          BESU_CONFIG_FILE: /opt/besu/config/config.tml
          BESU_BOOTNODES: "{{BOOTNODE}}"
        volumes:
          - "/var/besu/config:/opt/besu/config"
          - "/var/besu/database:/opt/besu/database"
        ports:
          - 30303:30303/udp
          - 30303:30303/tcp
          - 8545:8545/tcp
          - 8546:8546/tcp
        state: started

- name: BESU nodes deployment
  hosts: i3m-node4
  become: true
  tasks:
  
    - name: Get config files
      get_url:
        url: "{{ item.src }}"
        dest: "/var/besu/config/{{ item.dest }}"
        url_username: "{{NEXUS_USER}}"
        url_password: "{{NEXUS_PASS}}"
      loop:
        - { src: "{{URL_KEY4}}", dest: "key"}
        - { src: "{{URL_KEY_PUB4}}", dest: "key.pub"}

    - name: Run latest BESU docker image
      docker_container:
        name: besu
        image: hyperledger/besu:latest
        pull: yes
        env:
          BESU_CONFIG_FILE: /opt/besu/config/config.tml
          BESU_BOOTNODES: "{{BOOTNODE}}"
        volumes:
          - "/var/besu/config:/opt/besu/config"
          - "/var/besu/database:/opt/besu/database"
        ports:
          - 30303:30303/udp
          - 30303:30303/tcp
          - 8545:8545/tcp
          - 8546:8546/tcp
        state: started
