---
- name: sdk-core provisiong and publising
  hosts: i3m-node4
  become: true
  vars:
  tasks:
   - name: Get accee token for accesing to Sdk Generator REST API
     uri:
       method: POST
       url: "http://{{ KEYCLOAK_HOST }}:8080/auth/realms/i3market/protocol/openid-connect/token"
       body: "grant_type=password&client_id=SDKGeneratorClient&client_secret=a4279d93-994d-4de4-a2d6-3b1660d07842&scope=openid&username=i3market&password=sgfjlsn44r50.,fsf03"
       headers:
          Content-Type: "application/x-www-form-urlencoded"
     register: auth_request
   
   - debug:
       var: auth_request
       
   - debug:
       msg: " ACCESS-TOKEN: {{ auth_request.json.access_token }} "  
       
   - name: Make an API call to Backplane API to download OAS file
     shell: "curl -k -o -v \"/tmp/backplaneOAS.json\" https://{{ BACKPLANE_HOST }}:3000/openapi.json"
          
   - name: Display the OAS file contents
     shell: "cat /tmp/backplaneOAS.json"
     register: shellout        
   
   - name: Make an API call to SDK-Generator to generate SDK client stub
     uri:
       method: POST
       url: "http://{{ SDKGEN_HOST }}:8180/SdkGenerator/api/sdkgen/generateSDK/{{ LANG }}"
       body: "{ \"openAPIUrl\": \"https://{{ BACKPLANE_HOST }}:3000/openapi.json\" }"
       body_format: json
       validate_certs: no
       headers:
         Authorization: "Bearer {{ auth_request.json.access_token }}"
     register: sdkgen_results
     
   - debug:
       var: sdkgen_results 